### ISSUE TITLE
[Tracking] Abstractions and core libraries tooling - Java

### ISSUE THREAD

**Issue by baywet** [microsoft/kiota-java#32]
In order for us to move with confidence to GA, we need better tooling for the java abstraction and core libraries. This includes:

- [ ] microsoft/kiota-java#31
- [x] spotbugs
- [x] android api level linting + github workflow
- [x] javadoc for all the things that are not already javadoc in the abstraction libs (constructors, static things, not implementing/inheriting...)
- [x] cobertura reports generation
- [x] udpate the readmes to remove the tasks

**Comment by baywet** [comment]
spotbugs and coverage report generation has been added for abstractions in #101 but still needs to be added to the other packages
